Repository DininduChamikara/Annotated-Corpus-Collection, pull requests merged in 2024-10, with the labels that each got.

#46 fixed: instruction
  CONTRIBUTING.md
Labels: good first issue, hacktoberfest-accepted

#48 Added export in multiple datatype for pre-annotated data
  src/App.tsx
Labels: enhancement, hacktoberfest-accepted

#52 added a favicon and replaced the default react one
  public/favicon.ico
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#53 Adding tooltips to the buttons
  package-lock.json
  package.json
  src/App.tsx
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
